### ISSUE TITLE
Upgrade to ASP.NET Core 2.1

### ISSUE THREAD

**Issue by ardalis** [ardalis/CleanArchitecture#10]
Upgrade the Web project to ASP.NET Core 2.1.
Add a Pages folder and at least one Razor Page to show how they work.

**Comment by mcquiggd** [comment]
I'd be happy to take a look at this...

**Comment by ardalis** [comment]
Go for it; I'll welcome a PR. I'm guessing it should be a pretty quick/small set of changes. I'll probably keep it in a separate branch until 2.1 is RTM.

**Comment by mcquiggd** [comment]
Understood. Will take a look tomorrow.

**Comment by camainc** [comment]
I was just going to ask why the sample project does not make use of Razor pages. Your e-book "Architecting Modern Web Apps," on page 46, says "Razor pages simplify the process of building
individual pages in an ASP.NET Core app, while still providing all the architectural features of ASP.NET
Core MVC. They are a good default choice for new page-based functionality."

Looking forward to seeing this functionality added to the sample project. Great work!

P.S. I just finished watching the PluralSight course on DDD fundamentals, and really enjoyed it.

**Comment by mcquiggd** [comment]
Apologies for not completing this yet - just received a new job offer and have been planning relocation.

Will return to this tomorrow.

**Comment by mcquiggd** [comment]
And, not be able to this any time soon. Apologies. Moving to another continent with my family in 10 days.
