### ISSUE TITLE
Autofac with IHostBuilder

### ISSUE THREAD

**Issue by SandhyaGidda** [ardalis/CleanArchitecture#100]
Hi Ardalis,

Thank you for the wonderful CleanArchitecture solution.
As most of the forums recommend to use IHostBuilder, I tried changing to IHostBuilder and implement Autofac(as per this document) in your solution - https://autofaccn.readthedocs.io/en/latest/integration/aspnetcore.html#asp-net-core-3-0-and-generic-hosting

But not able to build the solution successfully.  Is it possible to update your solution which uses IHostBuilder compatible with Autofac. 

Thanks in Advance.

**Comment by ardalis** [comment]
Yes, I recently ran into this in a related solution and plan on fixing it here.

**Comment by SandhyaGidda** [comment]
That's great help Ardalis. I will wait for your update.

**Comment by SandhyaGidda** [comment]
Hi Ardalis,
Do you have chance to update your source code with IHostBuilder?

**Comment by ardalis** [comment]
I'll try and make time for this soon.

**Comment by SandhyaGidda** [comment]
Thanks for the update Ardalis. That will be big help!

**Comment by ardalis** [comment]
You're welcome. Hopefully fixed by PR #106
