### ISSUE TITLE
[Question]Should domain events be processed in order?

### ISSUE THREAD

**Issue by pauldbentley** [ardalis/CleanArchitecture#101]
The `BaseDomainEvent` class has a `DateOccurred` property, but when dispatching the events this isn't used.  Should the order of events be important or should it not matter in which order they are handled?

**Comment by ardalis** [comment]
It's sometimes useful to know when events occurred, especially if they're used for cross-domain messaging (e.g. integration events). If you're not using that property, feel free to eliminate it. As to whether the order of processing events matters, that really depends on the event and the domain. In some domains and scenarios it will be critical (perhaps processing ticket sales or hotel reservations) and in others it won't really matter (sending notifications/emails).

What I'm asked more often is about how to order handling of individual events, which is another way to think about it. In that case you can order your handlers by some property (e.g. Sequence or Priority) or you can chain your handlers by using events (event A triggers handler AH which dispatches event B triggering handler BH, and so on), or other variants. They all have pros and cons.

**Comment by pauldbentley** [comment]
Thank you for the information.  I think in my domain it is important to handle the events in order, I just wanted to make sure that this wasn't highlighting something wrong with my approach.
