### ISSUE TITLE
Using connection string from appsettings.json in StartupSetup.

### ISSUE THREAD

**Issue by zn** [ardalis/CleanArchitecture#102]
Hello everyone!
In [StartupSetup](https://github.com/ardalis/CleanArchitecture/blob/master/src/CleanArchitecture.Infrastructure/StartupSetup.cs#L11) the connection string is hard-coded. What if I want to use one from appsettings.json?
Is it ok if I'll add a parameter `connectionString` to your method:
``` C#
public static void AddDbContext(this IServiceCollection services, string connectionString) =>
            services.AddDbContext<AppDbContext>(options =>
                options.UseSqlServer(connectionString));
```
And just pass the connection string as an argument from `Startup`?
``` C#
services.AddDbContext(Configuration.GetConnectionString("DefaultConnection"));

**Comment by ardalis** [comment]
Yes, I'll fix that unless someone beats me to it.
