### ISSUE TITLE
None of the API controllers are consumed

### ISSUE THREAD

**Issue by ghanavat** [ardalis/CleanArchitecture#104]
When the project is running, under the To Do Items (MVC) section we have a link called: **Load Sample To Do Items (API call ...)**. But this does not call the API controller (ToDoItemsController), instead it calls the MVC controller, Populate action that returns a number. In fact, none of the APIs all called/consumed.

**Comment by ardalis** [comment]
They're accessible from the Swagger link in the home page:
![image](https://user-images.githubusercontent.com/782127/80241840-5291e000-8632-11ea-8be4-4804a56ea0da.png)

which leads to:
![image](https://user-images.githubusercontent.com/782127/80241863-5cb3de80-8632-11ea-8e2a-1b8a7af37315.png)

Is that sufficient? Normally the APIs would be consumed by other applications or a front-end like Angular, etc.

**Comment by ghanavat** [comment]
Yes that is sufficient. I was under the impression that the APIs would be used in the same UI. Thanks for responding!
