### ISSUE TITLE
Deleted entities with events do not trigger events

### ISSUE THREAD

**Issue by beukerz** [ardalis/CleanArchitecture#107]
Hello,
Thanks for this great template. I use it a lot.

One thing I noticed is if you add events to an entity you delete the event is not dispatched because the deleted entity is not found in the change tracker after save changes is completed. I have fixed it here by getting all the deleted items before save changes is executed:

public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = new CancellationToken())
        {
           // get deleted entities before save changes
            var deletedEntities = ChangeTracker.Entries<BaseEntity>()
                .Where(e => e.State == EntityState.Deleted)
                .Select(e => e.Entity)
                .Where(e => e.Events.Any())
                .ToArray();

            int result = await base.SaveChangesAsync(cancellationToken).ConfigureAwait(false);

            // ignore events if no dispatcher provided
            if (_dispatcher == null) return result;

            // dispatch events only if save was successful
            var entitiesWithEvents = ChangeTracker.Entries<BaseEntity>()
                .Select(e => e.Entity)
                .Where(e => e.Events.Any())
                .ToArray();

            // add deleted entities with events
            entitiesWithEvents = entitiesWithEvents.Concat(deletedEntities).ToArray();

            foreach (var entity in entitiesWithEvents)
            {
                var events = entity.Events.ToArray();
                entity.Events.Clear();
                foreach (var domainEvent in events)
                {
                    await _dispatcher.Dispatch(domainEvent).ConfigureAwait(false);
                }
            }

            return result;
        }

Thanks for the template one again!
Hugo

**Comment by ardalis** [comment]
That's interesting. I don't know that every use case would want events to be fired from deleted entities. But assuming you do, this is a good thing to fix.

I'm not sure it makes sense to always fire events on deleted entities, especially since most of my events I raise from entities include a reference to the entity itself. If it's been deleted, event handlers for this entity are likely to have problems.

Closing - feel free to reply if you have more questions.
