### ISSUE TITLE
Question: How to avoid duplicate entity between core and infrastructure?

### ISSUE THREAD

**Issue by pei-wang** [ardalis/CleanArchitecture#113]
For example, when I use the entity framework(ORM) to access the database, I need to create one entity for it. If the table column name is not Camel case format or table name is different with entity name, I also need to add some attributes on the field.

On the old N-tiers layers application, I can reuse it across all layers.
But on clean architecture, If I define the entity on the core, I still need to depend on entity framework, since I need these attributes.

so How do I handle this situation? should I create two similar classes?

**Comment by CesarD** [comment]
Mapping with attributes should not be used anymore. That generates (like you said yourself) coupling with the ORM, and that's why EF has the fluent configuration; so your classes can really be POCOs and not something with ORM decorations.

**Comment by ardalis** [comment]
@CesarD is right. You should configure any table mapping or column mapping from your entities (defined only in Core) to your database in configuration files in the Infrastructure project.

An example is provided here:
https://github.com/ardalis/CleanArchitecture/blob/master/src/CleanArchitecture.Infrastructure/Data/Config/ToDoConfiguration.cs

There shouldn't be any duplicate entity classes. Thanks!

**Comment by pei-wang** [comment]
Thanks @ardalis and @CesarD . Using fluent configuration can resolve the issue perfectly on dotnet project. I was thinking create DAO to query data from database, and create another mapper to map DAO to Domain entity.
