### ISSUE TITLE
Template not taking Project Name in consideration while creating new project

### ISSUE THREAD

**Issue by prohyred** [ardalis/CleanArchitecture#115]
When this template is used to create new solution. All the project should be created with the project name given. It's creating all project with name CleanArchitecture expect the solution name,

**Comment by ThomasCork** [comment]
This issue is also logged in Greg's fork for the template. 
https://github.com/GregTrevellick/CleanArchitecture/issues/18

**Comment by ardalis** [comment]
@GregTrevellick any update on this?

**Comment by GregTrevellick** [comment]
Hmmm....should be fixed in v1.0.20 of the vsix, I will retest this evening

**Comment by GregTrevellick** [comment]
Yes, just checked my local is running 1.0.20 (VS2019) and both projects & namespaces are the intended name, not "CleanArchitecture"

**Comment by ardalis** [comment]
Yay! Thanks! Closing this.
