### ISSUE TITLE
Where is Ardalis.ListStartupServices project ?

### ISSUE THREAD

**Issue by jasper22** [ardalis/CleanArchitecture#121]
Hi

May be I'm missing something but where is actually `Ardalis.ListStartupServices` project ? It reference in `CleanArchitecture/src/CleanArchitecture.Web/Startup.cs` at: [1 line](https://github.com/ardalis/CleanArchitecture/blob/18fa4b01b32e8e885ff780713f23b1960033e823/src/CleanArchitecture.Web/Startup.cs#L1) and [line 52](https://github.com/ardalis/CleanArchitecture/blob/18fa4b01b32e8e885ff780713f23b1960033e823/src/CleanArchitecture.Web/Startup.cs#L52). It actually should reference all start-up services for ASP .NET because there's no `services.AddScoped()` or `services.AddSingleton()`....

**Comment by ardalis** [comment]
It's a NuGet package:
https://www.nuget.org/packages/Ardalis.ListStartupServices/

Source is here:
https://github.com/ardalis/AspNetCoreStartupServices

It's purely used for debugging/diagnostic purposes.
