### ISSUE TITLE
Add example of multiple database contexts

### ISSUE THREAD

**Issue by lankymart** [ardalis/CleanArchitecture#122]
Would it be worth adding examples of multiple database context to align with DDD principles like bounded contexts and see how multiple contexts are implemented even if they use the same physical persistence store?

**Comment by ardalis** [comment]
Thanks for the suggestion! Typically I prefer to use different solutions for different bounded contexts if possible but you certainly can support multiple within a solution. This is meant to be a solution template, not a full sample application, though, so in the interest of simplicity I don't think I will add multiple DbContexts. You can see an example of a similar architecture that does have that here though:
https://github.com/dotnet-architecture/eShopOnWeb
