### ISSUE TITLE
Authetnication support using Identity Server

### ISSUE THREAD

**Issue by paragpkulkarni** [ardalis/CleanArchitecture#125]
Authentication is fairly common requirement in most of the projects. It would be nice if we add authentication support using [IdentityServer](https://github.com/IdentityServer) to this starter kit. Developers can quickly add Active directory, Google, Github and any other OpenID connect provider for authentication using Identity server.

**Comment by ardalis** [comment]
It is common but I don't think it should be in a base solution template. I'd be happy to have a separate branch or repo with it, though.
