### ISSUE TITLE
Autofac with WebApplicationFactory

### ISSUE THREAD

**Issue by ThiboTouch** [ardalis/CleanArchitecture#127]
We are registering all services defined in our core on the DefaultInfrastructureModule. Now there's a point in our end-end tests where we'd like to replace things such as sending emails or sms' to be resolved with mocks. I've gone through some articles but I still haven't found a better way to replace the DefaultInfrastructureModule with a definition that has mocked services on the build of the WebApplicationFactory. Is there anyway for this to be done in a clean way?

**Comment by ardalis** [comment]
What I usually do is use environments. Startup has good support for Environments, and will call a different ConfigureServices method for a given Environment. For instance, configure your WebApplicationFactory to use Environment "Testing" and then define `ConfigureTestingServices` in Startup and that's the one that will be called.

You can then set things up like this (one of several possible designs):
```
public bool IsInfrastructureConfigured { get; set; } = false;

public void ConfigureTestingServices()
{
  // call mock infrastructure services method or just do it here
  IsInfrastructureConfigured = true;
  ConfigureServices();
}

public void ConfigureServices()
{
  // do all the stuff you do now
  if(!IsInfrastructureConfigured)
  {
    // load infrastructure services from DefaultInfrastructureModule
  }
}
```
Admittedly this doesn't really show how to do it with Autofac but I'm guessing you can tweak it to work in that case, again taking advantage of environments.

**Comment by ThiboTouch** [comment]
Got it i configure inmemorey data on ConfigureTestinServices for "Testing" Environment.
useful links:

https://github.com/dotnet/aspnetcore/issues/14907#issuecomment-620750841

https://blog.johnnyreilly.com/2020/05/autofac-webapplicationfactory-and.html
