### ISSUE TITLE
How to handle unit of work?

### ISSUE THREAD

**Issue by thiennn** [ardalis/CleanArchitecture#133]
Hello,

I just take a quick look at this project. There is a question pop-up in my mind. How to handle unit of work? As I am viewing the EfRepository I see that `await _dbContext.SaveChangesAsync();` is called every time in Add, Update, Delete. Because in the real applications, we often call add/update,delete many times in a request, and then call SaveChangeAsync() once. Ef Core will take care the UoW for us.

https://github.com/ardalis/CleanArchitecture/blob/1643ef3544916719babc862a7e7813dec6f74b5b/src/CleanArchitecture.Infrastructure/Data/EfRepository.cs#L45

**Comment by ardalis** [comment]
I usually use the Aggregate pattern and typically only deal with a single aggregate per request, so UoW isn't a big deal. If you need it, it's easy to add. Just add a `Save` or `Commit` method to the `IAsyncRepository` and have that call `SaveChangesAsync`. For me it wasn't worth having the extra call to have to make every time (or add a filter to do it automatically), but if it helps you then by all means add it in your project.
