### ISSUE TITLE
Endpoints vs ApiController

### ISSUE THREAD

**Issue by DaveShopCtrl** [ardalis/CleanArchitecture#142]
Hi,

Finally I'm working on a greenfield project. So instead of adopting many clean architecture patterns into our brownfield application framework, I was finally able to start a product using the CleanArchitecture project template.

The Web project contains two api-like structures. First there is the ToDoItemsController in the /api folder. But Endpoints/ToDo folder seems to have disconnected the appi endpoints into separate classes. However both seem to implement the same thing.

Do I need to pick one and delete the other, or do they need to co-exist in the application. 
I'm leaning towards the first as repetition of code is a bad thing.

The readme.md file does not specify the intend behind both strategies.
Thanks for any clarification!

**Comment by ardalis** [comment]
You should pick. They can coexist, but for a new project you should standardize on one approach. I prefer ApiEndpoints but I don't want to dictate that for everyone who uses the CleanArchitecture template. I'll make a note to update the ReadMe accordingly. Thanks!
