### ISSUE TITLE
When Specification is applied? Use in another framework  

### ISSUE THREAD

**Issue by lehoangphan** [ardalis/CleanArchitecture#147]
I see the ApplySpecification<T> in EfRepository.cs (this template) 

But this apply when 

-before Query is executed

Or

-Filter after the data is complete Queried? (In-memory) ? 

----------------
Can i use this style specification if I use another library like Linq2Mongodb ? Do I need to override another SpecificationEvaluator? 

Thanks

**Comment by ardalis** [comment]
The Ardalis.Specification package could work with any expression-based ORM. The Ardalis.Specification.EfCore package is EF specific. The queries are run on the database (translated by EF) by default if you're using the EF Core package.

**Comment by lehoangphan** [comment]
thanks !
