### ISSUE TITLE
Select specific Field/Column with Specification Pattern ? 

### ISSUE THREAD

**Issue by lehoangphan** [ardalis/CleanArchitecture#148]
If we use the Specification Pattern in this template, can we just Select specific field in when Query ? 
Example: 
```
class Animal {
string Name 
int Id
int Age
}
```
but we just Select Name + Id in result,
Age will be null 

In Specification<T>.ISpecificationBuilder Query, I just see the 

`Where(Expression<Func<T, bool>> criteria) `
but not 
`Select()`

thanks

**Comment by ardalis** [comment]
Get the latest version of Ardalis.Specification and it has the .Select features. Check the samples. We also just did a YouTube walkthrough.
https://github.com/ardalis/Specification
https://www.youtube.com/watch?v=BgWWbBUWyig

I'll upgrade the version used by this template at some point, probably after .NET 5 ships.

**Comment by lehoangphan** [comment]
thanks !
