### ISSUE TITLE
How would you implement a mobile app with this solution?

### ISSUE THREAD

**Issue by saciervo** [ardalis/CleanArchitecture#160]
On one side, I don't want to include the Core project assembly in the deliverables. Because some services may contain business logic I do not want to expose. Also, it contains code that is simply not needed for the mobile app, but for the web app. But on the other side, I definitely need some Entities and Interfaces from the Core project in the mobile app. So, I have to reference it (and therefore deliver it) to the customers.

Do you have any suggestions on how to do this?

**Comment by Blackclaws** [comment]
My two cents on this as we had to think about a similar situation. If you really want to share your base entities between your mobile app and the backend then it makes sense to actually create another project that holds those base entities/aggregate roots and simply reference that package from your mobile app and your server. 

Something to think about however is whether sharing your actual implementation will do you any good, as the communication between the backend and any frontend will usually always involve data transfer objects, so as not to expose too much information inadvertently. If you now separate your frontend and backend Entities you can version them independently from each other and in principle can split up the work between two teams, on the other hand you might end up with code duplication, but maybe also a slimmer footprint on the frontend side as some properties of your entities might not be relevant in a certain context.

**Comment by ardalis** [comment]
You could use this as the back end and then the mobile (or SPA or Blazor or whatever) projects would be added to the solution, or in a separate solution. You can see an example, using Blazor WebAssembly as the client, in the eShopOnWeb sample here:
https://github.com/dotnet-architecture/eShopOnWeb
