### ISSUE TITLE
Complex Infrastructure Service as seprate Proejct?

### ISSUE THREAD

**Issue by MG110417** [ardalis/CleanArchitecture#162]
Hello,

In your example, you have EmailSender as Infrastructure service and it's interface IEmailSender is defined in Application Layer. But lets say that Email Service gets very complex, for example in my application I have functions like SendResetPasswordEmail(PasswordResetRequest request)   SendSignupEmail(SignUpEmailRequest request) etc. And all those Requests are Model/Dto classes. Email Service reads some HTML template and populates the data based on Request Models. So my Email Service has about 12-15 Classes in total.

In that scenario, would you suggest having a completely separate project for Email management and just add the reference into the Application layer? Or would you still prefer to do all the Implementation of the Email Classes in the Infrastructure Layer??

**Comment by ardalis** [comment]
`IEmailSender` is very low level - it just sends an email given what you send it.

If you need to do a lot of business logic in terms of different kinds of emails with different templates, etc. then I would define the business logic of these services as interfaces in Core. I would try to put as much of the logic into a domain service in Core. I would leave the *implementation details* of actually building emails from templates and actually sending emails to other interfaces that had low-level implementations in Infrastructure.

For example, maybe your basic version uses simple string.Replace tokens for your templates and local SMTP for sending. So you might have implementations for `StringReplaceMailTemplateService` and `LocalSmtpMailSender`.

But then later you start using Razor for your templates and SendGrid for sending, so you add
`RazorMailTemplateService` and `SendGridMailSender`.

The idea is to keep the high level concepts separate from the low level details. Put the "what" you need to do in Core; put the "how" you do it in Infrastructure.
