### ISSUE TITLE
Feature Request: Use Cases / Background task with api and DbContext

### ISSUE THREAD

**Issue by codejunction** [ardalis/CleanArchitecture#167]
Can you create a branch for api with async backround job in an api using the scoped dbcontext

Use case

1. async API call with immediate response
2. trigger background job using dbcontext from .net core di container

**Comment by ardalis** [comment]
I have some examples of this in my Pluralsight DDD course sample here:

https://github.com/ardalis/pluralsight-ddd-fundamentals
