### ISSUE TITLE
List Services

### ISSUE THREAD

**Issue by muratyuceer** [ardalis/CleanArchitecture#170]
// add list services for diagnostic purposes - see https://github.com/ardalis/AspNetCoreStartupServices
            services.Configure<ServiceConfig>(config =>
            {
                config.Services = new List<ServiceDescriptor>(services);

                // optional - default path to view services is /listallservices - recommended to choose your own path
                config.Path = "/listservices";
            });

method does not work as expected. Not all services listed

**Comment by ardalis** [comment]
What services are missing? Can you post output and what services you have registered?

Folks can certainly remove this package if they're not using it. And if it has bugs, it has its own repo where issues can be logged.

Thanks!

**Comment by ardalis** [comment]
Log an issue here if needed: https://github.com/ardalis/AspNetCoreStartupServices

Closing here.
