### ISSUE TITLE
Question about Core Layer instead of separated Domain and Application

### ISSUE THREAD

**Issue by agausachs** [ardalis/CleanArchitecture#172]
Hi Steve,
This project has really helped me a lot to understand clean-architecture principles. But when I look at other DDD or Clean Architecture projects/tutorials, people use to split the core layer in two, Domain and Application.  The only point I think it's better in the two layers approach is to isolate Domain layer from any other reference (or nuget packages), for the rest I think a single layer is easier to organize and mantain.

I would like to know your opinion on this two-core-layers approach, or if you find benefits on using a single core layer.

Thanks in advance!

**Comment by mehdihadeli** [comment]
Hi Steve,
I'm agree with @agausachs, I think separation on `core` layer to `application` and `domain` layer is cleaner approach also it is better for implementing application with DDD.

**Comment by ardalis** [comment]
What problem do you feel this extra layer (and, presumably, project) solves? I've been using the approach shown in this template for many years on many real world projects and I'm not seeing where an extra layer that makes it harder to actually work with the domain model would be a net benefit.

**Comment by agausachs** [comment]
I can't see the benefits of two layers for core further than a little more organization (but also adding more complexity). I was just asking to try to understand why there are devs that prefer that approach over one single layer.

Thanks!
