### ISSUE TITLE
SqliteException: SQLite Error 1: 'no such table: Projects'.

### ISSUE THREAD

**Issue by fspataro** [ardalis/CleanArchitecture#197]
- .NET SDK Version: 5

Steps to Reproduce:

1. Visual Studio, start new project from template item, build, run via buttons
2. Main page loads fine, swagger loads fine
3. Click on the any of the 'Projects' links for MVC or Pages 
4. Error is thrown.. 

Sorry, there's probably an easy step to initialize the sqllite db (i think the last version of the project had an api call for it?) but i'm not finding anything in the tutorial info.

**Comment by yuriburger** [comment]
If you remove the database.sqlite file from the web app root, it should recreate and seed the db correctly on the next run.

**Comment by ardalis** [comment]
@fspataro did @yuriburger 's response help?

**Comment by fspataro** [comment]
@ardalis @yuriburger sorry for the delay, busy week... 
Yes! Deleting the sqlite file solved the problem.  Closing the item.
