### ISSUE TITLE
New Project from template has ambiguous method call to IReadRepositoryBase

### ISSUE THREAD

**Issue by roflmuffin** [ardalis/CleanArchitecture#209]
- .NET SDK Version: 5.0.101

Steps to Reproduce:

1. Create fresh project from template.
2. Build solution using `dotnet build`
3. Receive error message.

```
<ProjectName>.Core\Services\ToDoItemSearchService.cs(38,45): error CS0121: The call is ambiguous between the following methods or properties: 'IReadRepositoryBase<T>.GetBySpecAsync<Spec>(Spec, CancellationToken)' and 'IReadRepositoryBase<T>.GetBySpecAsync<Spec>(Spec, CancellationToken)'
```

**Comment by ardalis** [comment]
Interesting timing - I just posted a reference issue covering this 2 hours ago based on another user's feedback. Can you check #208 and see if it solves your issue?

**Comment by roflmuffin** [comment]
Thanks Steve, updating to the latest .NET SDK has fixed the issue. Sorry I did check the closed issues earlier today but only lodged an issue when I got home, thanks!

**Comment by ardalis** [comment]
No worries. Like I said, it was interesting timing :).
