### ISSUE TITLE
Any chance of adding AddTodo view sample with handling of model validation errors?

### ISSUE THREAD

**Issue by politigf** [ardalis/CleanArchitecture#22]
First off, thank you for your work on this, it is a great starter template to get an idea of how to organize things.
Is there any chance you could add a sample AddToDo view that demonstrates how a view utilizes the api and handles any validation errors from it?

**Comment by facurodriguez** [comment]
Maybe what's here serves you: https://github.com/ardalis/ddd-guestbook

**Comment by ardalis** [comment]
Good call, @facurodriguez . 

Maybe I'll add a link to that from the README for this project. I do want to keep it more as a solution starter template than a full-blown sample application. That means keeping it small so when you create a solution from it you don't have a ton of junk to delete. Does the DDD-Guestbook sample help you, @politigf ?

**Comment by ardalis** [comment]
Either is fine. If you're using Views you'll probably use POST to controllers. If Razor Pages, then POST to the page. If a SPA (Angular, etc.) or desktop/mobile front end, then probably you'll POST to an API controller. In each case, the POST goes to a UI type (controller or page) but the business logic is performed by types in the domain model in Core project. HTH.
