### ISSUE TITLE
How to implement baseEntity primary key with Generic?

### ISSUE THREAD

**Issue by xie007** [ardalis/CleanArchitecture#249]
```c#
namespace CleanArchitecture.SharedKernel
{
    // This can be modified to BaseEntity<TId> to support multiple key types (e.g. Guid)
    public abstract class BaseEntity
    {
        public int Id { get; set; }

        public List<BaseDomainEvent> Events = new List<BaseDomainEvent>();
    }
}
```
and how wirte in AppDbContext class's SaveChangesAsync function?

```c#
        public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            int result = await base.SaveChangesAsync(cancellationToken).ConfigureAwait(false);

            // ignore events if no dispatcher provided
            if (_mediator == null) return result;

            // dispatch events only if save was successful
            var entitiesWithEvents = ChangeTracker.Entries<BaseEntity<int>>()
                .Select(e => e.Entity)
                .Where(e => e.Events.Any())
                .ToArray();

            foreach (var entity in entitiesWithEvents)
            {
                var events = entity.Events.ToArray();
                entity.Events.Clear();
                foreach (var domainEvent in events)
                {
                    await _mediator.Publish(domainEvent).ConfigureAwait(false);
                }
            }

            return result;
        }
```

my Entity

```c#
    public class Book: BaseEntity<Guid>, IAggregateRoot
    {

        public int Name{ get; private set; }
        ...

    }
```

my BaseEntity

```c#
    public abstract class BaseEntity<T>
    {
        public virtual T Id { get; protected set; }

        public List<BaseDomainEvent> Events = new List<BaseDomainEvent>();

    }
```

How to get primary key type?

when `int` should be ChangeTracker.Entries<BaseEntity<int>>(), if `Guid` how to implement?

**Comment by prabhpahul** [comment]
Facing the same issue. I tried making it generic but seems like no overload for SaveChangesAsync in Ef core is present. Should we implement a SaveChangesAsync() in EFCoreRepository?

**Comment by ardalis** [comment]
I see, so this line is causing problems:

```
var entitiesWithEvents = ChangeTracker.Entries<BaseEntity<int>>()
```

If you're only using Guid keys, then just change `int` to `Guid`.
If you're using both kinds of keys, the simplest approach is probably to just duplicate the query.

```csharp
// dispatch events only if save was successful
var entitiesWithEvents = ChangeTracker.Entries<BaseEntity<int>>()
    .Select(e => e.Entity)
    .Where(e => e.Events.Any())
    .ToArray();

foreach (var entity in entitiesWithEvents)
            {
                var events = entity.Events.ToArray();
                entity.Events.Clear();
                foreach (var domainEvent in events)
                {
                    await _mediator.Publish(domainEvent).ConfigureAwait(false);
                }
            }

var guidEntititesWithEvents = ChangeTracker.Entries<BaseEntity<Guid>>()
    .Select(e => e.Entity)
    .Where(e => e.Events.Any())
   .ToArray();
  

foreach (var entity in guidEntititesWithEvents )
            {
                var events = entity.Events.ToArray();
                entity.Events.Clear();
                foreach (var domainEvent in events)
                {
                    await _mediator.Publish(domainEvent).ConfigureAwait(false);
                }
            }
```

I'm sure there's a way to avoid all the above duplication but first see if that works and then see if you can make it cleaner.

**Comment by xie007** [comment]
Thanks @ardalis , I think it will be have cleaner method to solve this problem.

**Comment by prabhpahul** [comment]
Even though we override the query, how do we call for the specific instance or type method. As override for same  type would have same signatures.

**Comment by ardalis** [comment]
Are you still wondering about a `SaveChangesAsync` override, @prabhpahul ? You don't need a separate `SaveChanges` method per entity key type. Is the fact that its method signature is `public override async Task<int> SaveChangesAsync` and that includes `int` the thing that's confusing you? That `int` has nothing to do with entity key type. That integer value represents the number of rows the database operation(s) affected.

**Comment by prabhpahul** [comment]
Yes, it's known. The problem/confusion I see is the invoking different SaveChangesAsync depending upon ID type in Entity. For example: If I need to call it with GUID, I may have to call same method, how can we have different implementation for each type if supporting generic is a challenge.

**Comment by ardalis** [comment]
I don't understand why you think you need different SaveChangesAsync depending on the entity ID.

EF tracks changes in all of you entities, regardless of key type. When you call SaveChanges/Async it saves the changes to all of the entities that it's marked as changed. Regardless of key type.

Are you saying you *want* to be able to only save entities that have certain key types, for some reason?

**Comment by prabhpahul** [comment]
Oh so you meant, having traversal of different entities having different key types in same method, for example int and GUID in same saveasync method if we can have both in our app. I was thinking of keeping them separate. My bad.

**Comment by ardalis** [comment]
Let me know if you have any more questions. Closing this for now.
