### ISSUE TITLE
Update all projects to use VS2022 / .NET 6 project templates

### ISSUE THREAD

**Issue by ardalis** [ardalis/CleanArchitecture#260]
All projects in the solution should look as if they were created using the new .NET 6 project templates (xunit, api, and class lib)

**Comment by Coop56** [comment]
I'm going to start working through this ticket this weekend.

**Comment by ardalis** [comment]
All yours

**Comment by brokenthorn** [comment]
@Coop56 Hey, how's it going? Any idea when you're going to be finished?

**Comment by Coop56** [comment]
Haven't had a chance to work on this one yet, if someone else wants to pick it up feel free.

**Comment by Blackclaws** [comment]
Since we're using this template in a forked version internally for service development I'd be happy to contribute our .net 6 changes back here. If you'd like assign me to this issue and I'll put a pull request up in the next couple of days.

**Comment by Blackclaws** [comment]
It seems that some of the work has already been done now anyway, what I think is mostly missing is implicit usings, nullable by default and the top level statement program file without a startup class.
