### ISSUE TITLE
Validation Implementation

### ISSUE THREAD

**Issue by pradinski90** [ardalis/CleanArchitecture#267]
If you have 2 different projects, 1 API and 1 WEB. In both of those you have Action and Endpoint that is called Checkout 1) one is triggered via ajax calling the API/Endpoint and one being normal form submission via Post/Action in the web project. Both of those will have identical DTOs/ViewModels which will require identical validation.

1) How would you name them for the WEB and for the API ? Are you going to use one for both of them ? Where would you place them in the solution ?
2) If you want to send the request afterwards to a CommandHandler via Mediator where would you put the validation (On the mediator pipeline, on the WEB/API DTO as attributes or on Both) ? (required, max characters ....) Are you going to use the Command as DTOs/ViewModels for both the API and the WEB ?

Thank you

**Comment by ardalis** [comment]
Probably you want to keep duplication of business logic to a minimum. If you need to have identical behavior between the form POST and the API call then one way to achieve that would be to have the form POST make a call to the API and let the API be the "single source of truth" in terms of validation, etc. This would have a small performance cost and would couple the two projects together at runtime (so, if the API is down, the web project would also be effectively down, too).

If you're not going to couple them together, I'd probably keep everything separate, from DTOs to validators. I'd copy paste code as needed but I'd also let them evolve independently if necessary, allowing you to take advantage of their decoupled nature.

If you don't want them to vary from one another *and* you don't want to couple them together by having one call the other, then I'd put the shared DTOs and logic/validators into a nuget package that both use.

2. In addition to the above, if you want to add a MediatR pipeline to the mix, then the shared NuGet package could be the place where all of the validation happens. Define your commands and handlers and such and distribute the whole thing as a shared nuget package. Of course you can also define separate MediatR pipelines per project, etc. It's up to you how much combining you want to do. Just realize it has pros and cons (DRY but also coupled).
