### ISSUE TITLE
Moving from bower

### ISSUE THREAD

**Issue by Xeinaemm** [ardalis/CleanArchitecture#28]
Due to fact that [bower](https://docs.microsoft.com/en-us/aspnet/core/client-side/bower?view=aspnetcore-2.1) was deprecated(maintainers recommend using a different solution) for ASP.NET Core 2.1 we should switch to a different solution.

As Adam mentioned in this [post](https://bower.io/blog/2017/how-to-migrate-away-from-bower/) I would recommend Yarn as an alternative.

**Comment by ardalis** [comment]
The focus of this solution isn't on client-side dependencies at all. I'd be open to a PR to fix this, ideally based on non-bower web project templates shipping with dotnet CLI and/or Visual Studio.
