### ISSUE TITLE
Factories for testing

### ISSUE THREAD

**Issue by jaredcnance** [ardalis/CleanArchitecture#3]
First off, very cool project and thanks for doing this.

I would recommend structuring the test project to demonstrate / include factories for domain objects as opposed to [in-line instantiation](https://github.com/ardalis/CleanArchitecture/blob/master/tests/CleanArchitecture.Tests/Integration/Data/EfRepositoryShould.cs#L56-L59). Instead you would do something like:

```csharp
var todoItem = TodoItemsFactory.Get();
var todoItems = TodoItemsFactory.Get(5);
```

Internally, I would expect the factory to use something like [Bogus](https://github.com/bchavez/Bogus) or some other data 'faker'. I'd be happy to open a PR if you agree.

**Comment by ardalis** [comment]
Would like to see a PR for this that uses the Builder pattern. 
https://ardalis.com/improve-tests-with-the-builder-pattern-for-test-data
