### ISSUE TITLE
Remove ValueObject?

### ISSUE THREAD

**Issue by saraetx** [ardalis/CleanArchitecture#301]
Hi!

I see that this project contains [ValueObject](https://github.com/jhewlett/ValueObject) (but doesn't use it anywhere). It seems to me that it is now made redundant by record types.

Perhaps it should be removed now?

**Comment by ardalis** [comment]
No, there are good reasons not to use records as value objects, best explained here:
https://enterprisecraftsmanship.com/posts/csharp-records-value-objects/

However, I will try to add them to the default domain model since you're right, it would be good to see them in action.
