### ISSUE TITLE
Security Issue For Database Access

### ISSUE THREAD

**Issue by Chrisb2895** [ardalis/CleanArchitecture#312]
I've opened the code folders and seen that in Web Folder, inside appsettings.json there is the database connection string.
For security reasons, usually the web part which will be published online should not access the database or even contain DB access informations.
Usually I've seen that web part should be deployed on server1 and call an Internal Web Service (API) which is deployed on a dedicated server2 and only from the WebService Server2 you can access the DataBase.

Am I Wrong?

I would like to use your template but need to understand this security thing first.

**Comment by ardalis** [comment]
You shouldn't have any real connection strings in your source code. The only connection strings in this sample are for dev/demo purposes, using local file stores and Sqlite databases.

You're correct that in production you should use secrets that are accessible only from the production server, such as local environment variables or a secret store like Azure KeyVault.
