### ISSUE TITLE
Using database first approach - Clean Architecture

### ISSUE THREAD

**Issue by milyas-salik** [ardalis/CleanArchitecture#313]
Hi,

I am implementing clean architecture using the existing database, with scaffolding command I  have generated the POCO entities in the Infrastructure layer and as well as manually created the entities in the domain layer to map them later.

in the Application layer, I have the generic interface repository with a few standard operations.

   ```
 public interface IRepository<T> where T : class
    {
        Task<IReadOnlyList<T>> GetAllAsync();
        Task<T> GetByIdAsync(int id);
        Task<T> AddAsync(T entity);
        Task UpdateAsync(T entity);
        Task DeleteAsync(T entity);
    }
```

As per the principles of Clean-Architecture,  I am implementing it in the Infrastructure layer. 

```
public class Repository<T> : IRepository<T> where T : class
    {

        protected readonly MyDBContext _MyDBContext;
        public Repository( MyDBContext mydbContext)
        {
            _MyDBContext= mydbContext;
        }
        public async Task<T> AddAsync(T entity)
        {
            await _MyDBContext.Set<T>().AddAsync(entity);
            await _MyDBContext.SaveChangesAsync();
            return entity;
        }

-----
----
```

I am using a Mediator pattern with CQRS, when I try to save the user from the API layer I will end up with the below exception. 

`System.InvalidOperationException: Cannot create a DbSet for 'ABC.Domain.Entities.User' because this type is not included in the model for the context. However, the model contains an entity type with the same name in a different namespace: 'ABC.Infrastructure.Models.User'.`
 

It will be resolved if I can able to map the domain entity to the infrastructure entity in the above Repository implementation.
In the above implementation, the **T** is the ABC.Domain.Entities.User, not the ABC.Infrastructure.Models.User. I can't pass the ABC.Infrastructure.Models.User from the Application layer ( because I can't add a reference to the Infrastructure layer in Application layer) due to the rule **Clean Architecture all dependencies flow inwards and Core has no dependency on any other layer.**

Please help me to map the incoming domain entity with the infrastructure entity in the above repository implementation so that I can use these general methods for other entity operations as well.

@ardalis .. Please do the needful.

**Comment by ardalis** [comment]
You have two sets of types for your entities:

- Domain entities (ABC.Domain.Entities.User)
- Data entities (ABC.Infrastructure.Models.User)

The Domain entities should be defined in Core. The Repository interfaces should only be used with the domain entities. Repository is a domain pattern, and its interface should only reference or know about domain types. One way to force this is to change your generic constraint to instead of `where T : class` you have `where T : BaseEntity` where `BaseEntity` is defined in your domain model / core project.

Your data entities should only be used in your Infrastructure project. You may be able to mark them `internal` if you want to enforce this. Your web/api project should have no references to them.

All of this leads to a required fact: your repository is responsible for mapping from your DbSets and Data Entities to your Domain Entities.

HTH

**Comment by milyas-salik** [comment]
@ardalis  I agree with what you said, I am exactly using the same. 

I have generated the data entities with scaffolding in the infrastructure layer then created exactly the same domain entities in the domain layer.  But as you said, my repository interface (in the domain layer) only uses domain entities.

When I am doing insert operation from my controller my command maps my DTO to a business entity and repository implementation AddAsync (from Repostiroy. cs) will be called. And the exception throws.

Referring to your last statement **how would this domain entity be mapped to a data entity in the Repository in the infrastructure layer.** 

My question might be silly as I am implementing it the first time with EF DB first,  Can you share the syntax or guide me with the procedure.

I am sharing the code base link for the skeleton I am building.
https://gitlab.com/mail2mdilyas/workcontinent/-/tree/master

Please advise

**Comment by ardalis** [comment]
What you have here looks right (after cursory look): 
https://gitlab.com/mail2mdilyas/workcontinent/-/blob/master/Work.Continent.Infrastructure/Repositories/ProfessionalRepository.cs

For an insert, you'd just do something similar, mapping the `ProfessionalDomain` to a `ProfessionalInfra` before calling `DbSet.Add()` and `SaveChanges()`.

I don't see an Add method (yet) in your repo so I can't evaluate it specifically.

**Comment by milyas-salik** [comment]
@ardalis I agree with you. Check and Add the method here in the Repository.cs. 
https://gitlab.com/mail2mdilyas/workcontinent/-/blob/master/Work.Continent.Infrastructure/Repositories/Base/Repository.cs

The generic operations I implemented in the Repository.cs.

The "AddAsync" operation is in the generic repository (Repository.cs) and can be used for different insert operations with different domain entities in the future. 

And in this repository, I don't know what what is **T**  :
`public class Repository<T> : IRepository<T> where T : class`

Similar to the above link you shared, please advise me of the generic way to find and map the incoming domain entity with the data entity.

**Comment by ardalis** [comment]
T on the repo is always your domain entity.

**Comment by milyas-salik** [comment]
yes I knew it, how to map it to data entity in infra structure layer

**Comment by milyas-salik** [comment]
@ardalis 

The one way, I am thinking is to place get rid of the dependency with infrastructure entities (generated from the database using scaffolding) and use the domain entities with the model builder ==> modelBuilder.Entity - Professional class should be the one coming from your domain instead of infrastructure

As per me, this is the easier solution for DB first approaches using clean architecture. I need your advice on it, is it a valid tweek or do you advise using any other alternative solution? At the same time, I don't want to break the clean architecture rules as I want scalable and maintainable application in future.
