### ISSUE TITLE
Core Assembly and Data Annotations

### ISSUE THREAD

**Issue by pkharris** [ardalis/CleanArchitecture#32]
Any suggestions for adding data annotations to entities in the .Core project?  I added System.ComponentModel.Annotations Nuget package, but I'm not sure this feels right since .Core is .a NET Standard library.

**Comment by ardalis** [comment]
In projects where I've found this useful, I've gone ahead and added `System.ComponentModel.Annotations` to Core. I haven't seen any downside to it.

**Comment by pkharris** [comment]
Thank you for the response.
