### ISSUE TITLE
Include Blazor in template

### ISSUE THREAD

**Issue by mlenart1010** [ardalis/CleanArchitecture#344]
I would like to see how the Blazor WebAssembly project would fit into this template.

**Comment by ardalis** [comment]
You can see an example today of one way to set it up here:
https://github.com/dotnet-architecture/eShopOnWeb

I'll consider adding something to this template but I don't think most users of the template would necessarily need a Blazor client to go with it. Need to find a way to make such things modular, I guess.

**Comment by mlenart1010** [comment]
I did look at that also.  I am trying to follow the paradigm that is in eShopOnWeb along with your course on Inroduction to DDD with Julie.  In eShopOnWeb, what would be equivalent to SharedKernel and Web?

**Comment by ardalis** [comment]
There is no SharedKernel.
Web is the main ASPNET Core front end. Just like the front end in ClinicManagement or FrontDesk in the DDD course sample.

**Comment by mlenart1010** [comment]
So shouldnt there be a SharedKernel in eShopOnWeb??

So Web is equivalent to the FrontDesk.Api project?  If so then why are the endpoints in PublicApi?

**Comment by ardalis** [comment]
In a word: Auth.
The Pluralsight app didn't have logins or auth. The eShop web app uses cookie-based auth which doesn't always play nicely with token-based with. Using a separate project made it easier to have auth work correctly for both pages and API endpoints.
