### ISSUE TITLE
Hi ardalis: I have a question regarding the design

### ISSUE THREAD

**Issue by Nitinbabariya** [ardalis/CleanArchitecture#37]
Is this really a clean architecture?

I looked into the core, infrastructure and web...  code in all projects is arranged according to technology specific naming instead of user case/user flow oriented organization of code.
i.e. code is arrenged in entities, events, interface and services at higher level. Shouldn't it be arranged according to usecases

**Comment by ardalis** [comment]
Hi @Nitinbabariya,

This is meant to be a solution template that's pretty familiar to a typical .NET developer. Thus, it's not super opinionated about things like whether to use [feature folders](https://msdn.microsoft.com/en-us/magazine/mt763233.aspx) or use cases to organize functionality. Instead, it uses the default project structures used by Visual Studio. Personally, I'm a fan of organizing things according to [vertical slices ](https://deviq.com/vertical-slices/) or features, and often do this in my real world uses of this template.

There are a number of feature requests currently for things like use cases, CQRS support, MediatR integration, etc. which I'm considering. The only thing I have to weigh is whether the vast majority of users of this repo as a base solution template would see value in these. They may make more sense as separate branches. Open to feedback on this.

**Comment by dlacayo** [comment]
Hi @ardalis . I'm currently trying to wrap my head around clean architecture. Like you mention to @Nitinbabariya, having a branch with the use cases approach would be extremely helpful. Especially if we can compare it to the stock VS structure.

Thanks for your work!

**Comment by ardalis** [comment]
I've created a new issue to track use cases and feature folder organization for the template. See #82 for tracking. I'll try to move on it fairly soon.
