### ISSUE TITLE
Replace ValueObject implementation

### ISSUE THREAD

**Issue by MisinformedDNA** [ardalis/CleanArchitecture#375]
Should the current ValueObject be replaced with the [DDD Fundamentals ValueObject](https://github.com/ardalis/pluralsight-ddd-fundamentals/blob/main/SharedKernel/src/PluralsightDdd.SharedKernel/ValueObject.cs)? Or is there a reason they are different?

**Comment by ardalis** [comment]
Yes, probably. There are a bunch of different implementations but I do prefer the one I used in the DDD sample. Want to make a PR?

**Comment by ZarakiKanzaki** [comment]
Hi! @ardalis  may I contribute to this issue>??

**Comment by MisinformedDNA** [comment]
> Yes, probably. There are a bunch of different implementations but I do prefer the one I used in the DDD sample. Want to make a PR?

Sure thing.

**Comment by ardalis** [comment]
@MisinformedDNA it's all yours.

@ZarakiKanzaki if it's not done in a week feel free to hop in.
