### ISSUE TITLE
Remove libman dependencies

### ISSUE THREAD

**Issue by ardalis** [ardalis/CleanArchitecture#42]
Currently you can't build the project/solution if you don't have internet because of the libman dependencies (and because of nuget as well, but assuming you already have packages in your local nuget cache). This was an issue during a workshop today. There's no need in most cases for bootstrap/jquery to be in this template so these can be safely removed.

**Comment by PrintsCharming** [comment]
This could also be an issue like right now when, for some reason, Cloudflare isn't serving some of the assets until you go to the file location in your browser. I've been fighting a losing battle trying to get this to build right now.

**Comment by ardalis** [comment]
Not worth removing; will leave it since most projects probably need the client side files.
