### ISSUE TITLE
Layer Dependency

### ISSUE THREAD

**Issue by ehsanrezaee** [ardalis/CleanArchitecture#436]
Based on a Microsoft document, web(UI) layer should reference the application core project, no infrastructure project
What do you think?

![4A030632-3891-4FE9-9B37-D288DD1074D4](https://user-images.githubusercontent.com/11017659/193049369-1889e571-ceab-4b41-aa90-2a16c697f0bc.jpeg)
![E8861E70-B16C-4413-BC46-35BD0012FD73](https://user-images.githubusercontent.com/11017659/193049403-82292da1-41f1-4d68-a68f-d544a0dda6e8.jpeg)

**Comment by lukehammer** [comment]
This is a compelling idea, and I would anticipate that the web layer would be dependent on the core project. (and not acquire that dependency through the infrastructure project in a transitive manner)
You're right to note that the web project shouldn't contain infrastructure code. However, we do need to make an exception for setting up dependency injection because the web project functions as the application's entry point.


Even while we are permitted to reference the infrastructure project inside of the dependency injection setup, we shouldn't reference it in any other places within the web project


We could do a PR and reset these dependencies if that's what the group thing is right

**Comment by lukehammer** [comment]
“No direct instantiation or statics calls to the infrastructure layer types should be allowed in the UI layer”
that is definitely true I would say that referencing the infrastructure layer in the dependency injection setup falls outside of the scope of what you have cited. 

and last time I reviewed the code there was no this is a direct instantiation or static calls inside the web project.


it would be really cool if programmatically we could allow the infrastructure project to be referenced in the dependency injection but disallowed in the controllers and the other web components I currently don't think this is possible.

**Comment by ardalis** [comment]
One approach I've seen to avoid dependence on Infrastructure from within the application is to put the Controllers/Endpoints into a separate project, and have the UI (Web) project reference this. So, app startup and DI all happen in the entrypoint web project (of course), but all of the actual functionality (controllers, endpoints, filters, services, DTOs, etc.) is in another project. The entrypoint project is extremely thin. I haven't tried this on a real project myself but may give it a shot soon if I have time.

Of course another common approach is to delegate DI to another project. You can use autofac modules as one approach, or static helpers that extend ServiceCollection as another common one. Both of these can help remove Infrastructure dependencies from your UI/Web project.

Incidentally, I think I actually wrote the "Microsoft document" referenced in this issue description (but without a link to the source it's hard to say for sure). Obviously I'm familiar with the concepts described. If you want to ensure there are no project references to Infrastructure, in addition to the approaches I've covered above, you can also refer here:
https://ardalis.com/avoid-referencing-infrastructure-in-visual-studio-solutions/

**Comment by ehsanrezaee** [comment]
According to my experience and the Microsoft document, custom DI can solve this problem. In this way, the dependency of the web layer on the infrastructure layer is lost.
![B70A9302-3C4F-43A3-8788-6C9D04AD517B](https://user-images.githubusercontent.com/11017659/193240331-ea05ab29-b7d2-45e2-a189-a459bec19b5d.jpeg)

**Comment by ardalis** [comment]
Again, it would be nice if you were to link to "the Microsoft document" so folks know what you're talking about and quoting, @ehsanrezaee

**Comment by ardalis** [comment]
Just to follow up, you are in fact quoting the book I wrote, here:
https://learn.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/common-web-application-architectures#ui-layer-types

And yes, you *can* avoid referencing Infrastructure, but you don't *have* to. And most teams don't. So while I do try to be slightly opinionated with this template, I don't want to confuse people by making a change that isn't how most teams work.
