### ISSUE TITLE
Multi-tenancy over different dbs

### ISSUE THREAD

**Issue by lucaarpaia** [ardalis/CleanArchitecture#45]
Hi, as first thank you for sharing this valuable piece of code!
I'm evaluating to use cleanarchitecture as core building block of a project having multi-tenancy concept delivered by different physical DBs (each tenant in its db) and I wonder how I can adapt your solution to my case without incurring in problems related to ORM warm-up or db session/connection handling.
May be swap EF with Dapper would make life easier in this context?

**Comment by ayodahunsi** [comment]
Maybe we start with the simplest pattern (F) for now, see:
https://docs.microsoft.com/en-us/azure/sql-database/saas-tenancy-app-design-patterns.
I know @lucaarpaia wants (D) - a separate db per tenant.


Ayo (aka CodeStencil)

**Comment by ardalis** [comment]
To solve having multi-tenancy in a single database you would need to:

- Pull in the tenant ID from the route of each request (or from a cookie/header/querystring/etc)
- Add the tenant ID to any database query you performed. EF Core has a feature to support this*.
- Add the tenant ID to all entities that need to be tenant-specific

*[Global Query Filters](https://docs.microsoft.com/en-us/ef/core/querying/filters)

**Comment by ardalis** [comment]
This is probably a good idea to use as a separate sample that I could fork in another GitHub repository and link to from here.

**Comment by ardalis** [comment]
Closing for this repo. If someone implements a good sample forking off of this repo I'll be happy to link to it in the README.
