### ISSUE TITLE
How to handle Clean arthitecture multiple databases

### ISSUE THREAD

**Issue by iozcelik** [ardalis/CleanArchitecture#49]
As I understand, repositories are in infrastructure project. So I planning to refactor my project and I want to be sure about place of repository logics. 

In my case, I have 2 relational databases, one bigdata and one cache. So, in my case if data is in cache, I got it from cache. If not, I got relational db and put the cache and return data. It is inside in Business Logic. However, in my old project, usage of this layer has some disadvantages.

I try to understand how to clean arthitecture handle it?

**Comment by ardalis** [comment]
All of those are examples of infrastructure. Accessing each one should be in a separate class (or classes) in the infrastructure project. Let's say you have an entity Customer and Customer gets stored in either a SQL Server or it could be cached in Redis. Then you might have an interface ICustomerRepository and in Infrastructure an implementation called EfCustomerRepository or SqlCustomerRepository to access the relational db. And then another separate class implementing the same interface called RedisCustomerRepository that would check the Redis cache first, and then delegate to another ICustomerRepository (following the CachedRepositoryPattern I've described at length on ardalis.com).

If you had still more places you might persist data to/from, they would also be separate classes of the same (or maybe other) interfaces. In some cases it might make sense to have multiple Infrastructure projects, but I don't usually do this unless it gets large and cumbersome.

Does that help?

**Comment by kevonh** [comment]
@ardalis I looked for the CachedRepositoryPattern on your site and couldn't find it. Could you provide a link?

**Comment by ardalis** [comment]
https://ardalis.com/building-a-cachedrepository-in-aspnet-core

**Comment by efleming18** [comment]
Closing as this seems to be answered. Let's open up another issue if there are further questions.
