### ISSUE TITLE
Application Layer Or Application Service

### ISSUE THREAD

**Issue by vanasis** [ardalis/CleanArchitecture#503]
Hi, I read some articles about clean architecture and some of them said that there is a layer called application layer that handle the business logic and types.

_"The Domain layer contains the enterprise logic and types, and the Application layer contains the business logic and types"_

Is there any Application Layer or Application Service inside Ardalis/CleanArchitecture project?
Or interfaces inside core layer act as Application?
what about events folder, they handle domain business or application business or service

Is there any plan to decouple "CORE" layer to two separate parts like Domain and Application?

**Comment by ardalis** [comment]
Many applications don't really need a separate layer or project just for "application services" sometimes also called "use cases". My preference is to have such services, when needed, simple live in the UI project (in this case the Web project). They often benefit from returning DTOs defined in the Web project, just as ViewModels or API models, so it makes sense to put them in the same project as these DTOs. If you find the additional layer/project helpful, it should be trivial for you to add it, and no judgment from me on it. :)
