### ISSUE TITLE
Questions Startup.BuildDependencyInjectionProvider

### ISSUE THREAD

**Issue by JulidaRocks** [ardalis/CleanArchitecture#51]
There is an open ToDo in the Startup.cs:
`// TODO: Add Registry Classes to eliminate reference to Infrastructure`
What do you mean with "Registry Classes"?
Thank you

**Comment by ardalis** [comment]
Yeah that's been there a while now - I should clean it up.

It's referring to Structuremap Registry types, which allow you to place the interface-implementation mappings for your DI container into different classes. In this case you would have a registry class in each project that would handle registration there, and would eliminate the need for Startup to know about implementations in Infrastructure, for instance.

An example is here:
https://ardalis.com/avoid-referencing-infrastructure-in-visual-studio-solutions

Structuremap's obsolete and getting this working with EF Core was a pain so I never got to it. I'll at least remove the comment.

**Comment by amit-sonora** [comment]
Thanks Steve,
Does that mean we can not refer Infrastructure project using just a name in UI project? Is it a limitation of Autofac?
Thx
Amit
