### ISSUE TITLE
Getting started...

### ISSUE THREAD

**Issue by Crystal1462** [ardalis/CleanArchitecture#517]
- .NET SDK Version: 7

Just be new to the project and not sure where to start...
I did check the closed issues, stackoverflow and anything I could find in the project first.

Question/Issue
I am new to the project and really not sure where to start with it nor any readme file to just help get a new user started.  The ToDo aspect seems to be kind of lacking just enough functionality where you spend more time guessing then figuring out. Is there a decent example of this template in action I can at least delve into and figure things out?  If this is beyond the desired results of the project just let me know. thanks

**Comment by ardalis** [comment]
This is meant to be a template for new solutions not a sample app (though the todo stuff is there just so you can get any idea of how your app might be structured). For more guidance, ebook, video, etc check out the eShopOnWeb GitHub repo (readme links to books and video) and search YouTube for ardalis clean architecture for more.

https://github.com/dotnet-architecture/eShopOnWeb

**Comment by Crystal1462** [comment]
Perfect thank you, I did check out the eShopOnWeb project briefly just from the initial glance seen enough differences that I questioned myself how related.  I will dig deeper into it all.
