### ISSUE TITLE
Template Support for Visual Studio on MAC

### ISSUE THREAD

**Issue by khawars** [ardalis/CleanArchitecture#52]
Will template be supported for Visual Studio on MAC anytime later? Probably .mpack is needed.

**Comment by ardalis** [comment]
Shouldn't VS for Mac be able to just open the .sln and .csproj files?

**Comment by ThomasCork** [comment]
@ardalis I think @khawars is referring to the extension. 
https://github.com/ardalis/CleanArchitecture#using-the-visual-studio-item-template

All it does it creates the same files as cloning the repository right?

**Comment by ardalis** [comment]
From the point in time when it was last updated, yes. The latest files are always in the repo master branch.

One option would also be to create a template for the CLI do you could say `dotnet new clean` and have it do the right thing. Though that's probably worth a separate issue.

**Comment by ardalis** [comment]
You can use this template on a mac using the dotnet CLI:

https://github.com/ardalis/CleanArchitecture#using-the-dotnet-cli-template
