### ISSUE TITLE
Infrastructure Registry

### ISSUE THREAD

**Issue by amit-sonora** [ardalis/CleanArchitecture#53]
HI Steve,
I was trying to implement Infrastructure registry to remove reference of Infrastructure project from Web. But now code uses Autofac and your article on ardalis.com refers structuremap. I tried a lot but couldn't resolve it. can you please guide?

**Comment by jasonrmh** [comment]
I think the comment is redundant and registry no longer required as structure map is not used.

**Comment by jasonrmh** [comment]
See issue 51 for the same:
https://github.com/ardalis/CleanArchitecture/issues/51

**Comment by ardalis** [comment]
We switched to Autofac and it has Modules like this one:
https://github.com/ardalis/CleanArchitecture/blob/master/src/CleanArchitecture.Infrastructure/DefaultInfrastructureModule.cs
