### ISSUE TITLE
Not able to Install Extension on  VS 2022  V17.6.1

### ISSUE THREAD

**Issue by jigarce** [ardalis/CleanArchitecture#558]
26-May-23 9:46:44 PM - Microsoft VSIX Installer
26-May-23 9:46:44 PM - -------------------------------------------
26-May-23 9:46:44 PM - vsixinstaller.exe version:
26-May-23 9:46:44 PM - 17.6.2164+g40888c9894
26-May-23 9:46:44 PM - -------------------------------------------
26-May-23 9:46:44 PM - Command line parameters:
26-May-23 9:46:44 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\jigar\Downloads\vsixTemplatePackSideWaffle.vsix
26-May-23 9:46:44 PM - -------------------------------------------
26-May-23 9:46:44 PM - Microsoft VSIX Installer
26-May-23 9:46:44 PM - -------------------------------------------
26-May-23 9:46:45 PM - Initializing Install...
26-May-23 9:46:45 PM - Searching for applicable products...
26-May-23 9:46:45 PM - Found installed product - Visual Studio Professional 2022
26-May-23 9:46:45 PM - Found installed product - Global Location
26-May-23 9:46:45 PM - Extension Details...
26-May-23 9:46:45 PM - 	Identifier         : 3D68A845-300E-4D15-8EAA-28F9B51DB6BC
26-May-23 9:46:45 PM - 	Name               : Clean Architecture
26-May-23 9:46:45 PM - 	Author             : Greg Trevellick
26-May-23 9:46:45 PM - 	Version            : 1.0.22
26-May-23 9:46:45 PM - 	Description        : A template for a solution structure that can be used to build Domain-Driven Design (DDD)-based or simply well-factored, SOLID applications using .NET Core. 
26-May-23 9:46:45 PM - 	Locale             : en-US
26-May-23 9:46:45 PM - 	MoreInfoURL        : https://github.com/GregTrevellick/CleanArchitecture
26-May-23 9:46:45 PM - 	InstalledByMSI     : False
26-May-23 9:46:45 PM - 	SupportedFrameworkVersionRange : [4.5,)
26-May-23 9:46:45 PM - 	SignatureState     : Unsigned
26-May-23 9:46:45 PM - 	Supported Products : 
26-May-23 9:46:45 PM - 		Microsoft.VisualStudio.Community
26-May-23 9:46:45 PM - 			Version : [15.0,17.0)
26-May-23 9:46:45 PM - 			ProductArchitecture : x86
26-May-23 9:46:45 PM - 	References         : 
26-May-23 9:46:45 PM - 	Prerequisites      : 
26-May-23 9:46:45 PM - 		-------------------------------------------------------
26-May-23 9:46:45 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
26-May-23 9:46:45 PM - 		Name         : Visual Studio core editor
26-May-23 9:46:45 PM - 		Version      : [15.0,)
26-May-23 9:46:45 PM - Signature Details...
26-May-23 9:46:45 PM - 	Extension is not signed.
26-May-23 9:46:45 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by sadukie** [comment]
@jigarce Looks like you're trying to install the template in Visual Studio. That is in a different repo, maintained by someone else. You can find that repo here: [GregTrevellick/CleanArchitecture](https://github.com/GregTrevellick/CleanArchitecture)

**Comment by ardalis** [comment]
Yeah we haven't seen any updates to that extension in quite some time, unfortunately. I need to remove it from the README at this point, I think.
