### ISSUE TITLE
Project creation from template failed.

### ISSUE THREAD

**Issue by farhan9ali** [ardalis/CleanArchitecture#56]
while creating project after installation i got an error.
![image](https://user-images.githubusercontent.com/21053342/54527904-991b0280-497b-11e9-977a-52b5400e5310.png)

**Comment by ardalis** [comment]
@GregTrevellick can you help?

**Comment by efleming18** [comment]
Closing as I'm no longer able to reproduce. This should, however, be updated to use the latest .NET Core 3.0 version. I will open another issue for this.
