### ISSUE TITLE
Naming Issuse: shared kernal in DDD is for Domain logic, not for technical.

### ISSUE THREAD

**Issue by phiree** [ardalis/CleanArchitecture#577]
shared kernal is about domain , not technical.  i think it would be better to move it to Domain project and  rename it  to  Common/Base/Core/Helper..etc.

- .NET SDK Version:

Steps to Reproduce:

1.
2.

**Comment by ardalis** [comment]
Mostly agree but there's no reason it can't also include a few base types, and since the template has no knowledge of the actual domain that will be used, I didn't include anything domain-specific in it.
