### ISSUE TITLE
Infrastructure implementation details are leaking into Application layer

### ISSUE THREAD

**Issue by jbrinkman** [ardalis/CleanArchitecture#601]
The Web layer includes references to EFCore and AppDBContext.  This seems to violate the separation of concerns.  If I wish to switch from EFCore to Dapper I now have to change both the Infrastructure layer and the Web layer.  It feels like this could be refactored to include the appropriate extension methods in Infrastructure to register the needed Services and to execute any DB seed code as appropriate to the particular DB implementation.

**Comment by ardalis** [comment]
True, it could easily be moved but is currently there for convenience reasons. The use of an extension method would help at least with the project-level dependencies, although the runtime static dependency on the extension method would remain. Probably an improvement, though, thanks!

**Comment by hddhagai** [comment]
.net 6 version of the template had no reference to EFCore. Could you you please guide as to why this was added in  current template.

**Comment by ardalis** [comment]
I should probably refactor to address this concern; will do so when I get a chance. Thanks for the feedback.
