### ISSUE TITLE
looks AddSingleton not works

### ISSUE THREAD

**Issue by HighLordA** [ardalis/CleanArchitecture#62]
Hi guys
 when I use AddSingleton  before BuildDependencyInjectionProvider in startup.cs
when I resolve it from HomeController, it will be a new object everytime , think may be caused by BuildDependencyInjectionProvider with autofac?
 Thanks

**Comment by efleming18** [comment]
Hey @HighLordA - since this issue is a little older is this still an issue for you? If it is, could you provide a little more context, code snippets, etc so I can try to help out?

**Comment by ardalis** [comment]
Closing. Re-open if still an issue.
