### ISSUE TITLE
Use cases X traditional business layer

### ISSUE THREAD

**Issue by yncardoso** [ardalis/CleanArchitecture#66]
Hi @ardalis,

First of all, thanks for sharing this template with us. This might sound very basic but I was wondering where should I add the business logic? Let's say we have a payroll system. It needs to calculate the salary of the employees based on working hours, rates, taxes and etc. Where should I put this logic? I believe you'll answer the Use Cases layer. Is it correct to assume that the Use Cases layer is the same as the Business layer of a tradicional multilayered architecture?

Here's my current structure:

**Application**
 - core layer
   - core - entities, dto's and interfaces - including services (e.g IEmployeeService)
   - application - service implementations (e.g EmployeeService - business logic -> calculate salary)
 - infrastructure
   - infrastructure (third parties, identity, etc)
   - persistence (DbContext, repositories, migrations, etc)

Thanks,

Yuri

**Comment by ardalis** [comment]
In the current design I would try to add all business logic in the domain model in the Core project. I have a new tracking issue to add better support for use cases and feature-folder organization to the template at #82.
