### ISSUE TITLE
ORM related concepts influencing design of Core

### ISSUE THREAD

**Issue by Praveen-Rai** [ardalis/CleanArchitecture#67]
@ardalis , 

As per DDD, the core has to be agnostic to databases, presentation etc. But in practice i see that most of the design of core is still influenced by EF. The **BaseEntity** class is best example of it. 

Looking from the perspective of a Desktop application developer,  to me the dominance of POCO classes in an application seems to be influenced by RDBMS and ORMs. 

For e.g. below is how a ToDoApplication would look like if were not to consider RDBMS.

```
    public class Person
    {
        public string Name { get; set; }

        public List<ToDoItem> ToDos { get; set; }

        public List<ToDoItem> CompletedItems { get; }

        public void MarkItemAsCompleted(ToDoItem item) { }
    }

    public class ToDoItem
    {
        public string Title { get; set; }

        public void MarkAsCompletedFor(Person user) { }

        public List<Person> Persons { get; set; }

        public List<Person> CompletedBy { get; }
    }
```
If you completely let go of the ORM, then probably you'll not create the mapping entity ( Person-ToDoItem ) in your core. 

**The case of Lists**

In general, we use _Lists<T>_ to store ordered elements. For e.g. in the code below, as the list is ordered, we are probably going to use item index as a Serial number for the page.  

```
    public class Book
    {
        public string Title { get; set; }

        public List<Page> Content { get; set; }
    }

    public class Page
    {
        public string Title { get; set; }

        public string Content { get; set; }
    }
```

It is the RDBMS that needs SNo, and Foreign key in the Page entity to link a page to a book. And that shouldn't be a concern of the Core. Right ?

**Solution ( In my opinion )**

I feel the design of the _Core_ must be driven solely by the functional requirements. Meaning there must be functional classes and not entities, in the _Core_. Instead of having a _BaseEntity_ in core, i feel the _Database Layer_ must extend the _Core Classes_, create mapping entities if needed, do the splitting and merging or whatever is required to fit the needs of the ORM or RDBMS. In short, the _Core_ must have the functional classes, while the _Database Layer_ must generate the entities.

**Comment by gohalien** [comment]
That was the first thing I noticed. I also think Core project should only have only POCOs and business rules only. Entities should be moved to infrastructure/repo project, and set up the mapping rules.

**Comment by ardalis** [comment]
That's certainly an option, and I agree it's more _pure_. But it's also more effort, and I'm not sure there's much to be gained from it. I already get plenty of pushback from organizations and developers when I suggest that domain model types shouldn't be used as viewmodels or API wire format models. Now I would further need to convince them that there is good ROI involved in having a pure domain model of completely PI types that then is mapped to/from very-similar-but-not-quite-identical entity types in the Infrastructure project and also mapped to/from UI-level types?

One can certainly do that. And if it alleviates pain you're experiencing, please be my guest. This starting point is what I consider to be a pragmatic approach that follows SOLID and Separation of Concerns and DDD in a manner that has successfully solved business problems for hundreds of applications. It's not perfect and you should adapt it to suit your needs but I don't think I would have it default to having another set of types beyond what it has now.

**Comment by ssimontis** [comment]
I think there's a point of diminishing returns when it comes to architecture purity. Is the user going to notice that your abstractions are leaking out or not layered properly? Nope. Is the user going to be pissed when you're a month late refactoring things instead of adding features or fixing bugs and sympathize with your explanation about architecture? Also no. For a private project, do whatever pleases you. But when you are writing commercial software or really if you want other people to consider your software, your needs/concerns aren't the point. It's the users and potential users that matter and I think our entire industry has reached a point over the past few years where we forget what we're doing and get so caught up with ideas and shiny things that we forget about the human aspects of computing.

**Comment by ardalis** [comment]
Closing this as I'm not planning to take action on it. I'm happy to continue the discussion, though.

**Comment by calbeda** [comment]
I see a big (for me) problem here... let me explain:
For example, let's say I want to program doing a Unit test first approach. I would like to be able to do changes in my domain classes (for example adding new properties to be used in the tests), and I would like to do so without having side-effects in the infrastructure. 

This is not possible if domain classes are the Entities for EF! Any change in a domain class would immediately generate a migration.... this should not be happening and all!. Also, you know how complex are working with migrations in a team with many programmers if many people are changing the model at the same time (and if the team is sharing a database for development as is quite common, things get much worse).

Similar situations can happen if I there is a team working in UI that is developing new functionalities. If they are a UI focused team, they literally cannot be generating migrations for each change the do. Of course they will finish having a viewmodel classes where they will do the changes. That was not the idea of the Onion architecture, right?
