### ISSUE TITLE
Where should helper classes like TypeHelper, StringHelper etc be?

### ISSUE THREAD

**Issue by prince272** [ardalis/CleanArchitecture#70]
Should helper classes be inside the Core project or the Infrastructure project?

**Comment by prince272** [comment]
I just wanted to know how well you''ll be able to organize NopCommerce files using this  CleanArchitecture Template.

**Comment by Xeinaemm** [comment]
Code without external dependencies - core, but more likely you should create a shared library to keep reusable code and then link this as a dependency. 

Something like this: https://github.com/ardalis/CleanArchitecture/blob/95083acd1a7ab1f3be4c4f76733dfe4ed6810485/src/CleanArchitecture.Core/CleanArchitecture.Core.csproj#L9

From my perspective - I'm splitting Core into Contracts, Domain, Messages. Infrastructure into Persistence, Application, Application.Setup, Message broker. Web into UI, API(ie. API, ReadApi, PresentationApi).

Core
- Contracts - basic models, DTOs, the definition of endpoints for API.
- Messages - models as above but for Message Broker.
- Domain - domain models that hold business logic in entities and value objects without **EXTERNAL** implementation. Just domain, root objects, etc.

Infrastructure
- Application - implementation of business logic, CQRS that can handle DTO's and change domain by commands base on external resources(other API).
- Application.Setup - just setup to run a whole application like Autofac setup.
- Persistence - mapping of views, tables from DB
- Message Broker - CQRS implementation of handlers and system that run message broker service (write mode)

Web
- API - POST Actions that invoke CQRS and then message broker(yep, next CQRS system)
- ReadAPI - internal/external definition of data that your or any system can get
- PresentationApi internal read data for UI

**Comment by ardalis** [comment]
I'd agree with @Xeinaemm
