### ISSUE TITLE
How to use IRepository and load foreign key objects?

### ISSUE THREAD

**Issue by michelschep** [ardalis/CleanArchitecture#72]
Hi Steve,

How can I use the List method

```
public List<T> List<T>() where T : BaseEntity
        {
            return _dbContext.Set<T>().ToList();
        }
```
and still use Include to load referencial data in case T is a child and wants to refer to a parent object?

After doing ToList() in List<T>() the client class using IRepository can no longer do that.
Or am I missing something?

Kind regards,

Michel

**Comment by kworld-fr** [comment]
I asked myself the same question a little while ago.
If i not misunderstood, the version of IRepository presented here is more or less limited to CRUD.

I think the answer given by @ardalis on ticket #38  will help you.

**Comment by ardalis** [comment]
Correct. A more full-featured repository with specification support is described there. You can also use my new Ardalis.Specification nuget package if you don't want to copy/paste all that code into your project.

https://www.nuget.org/packages/Ardalis.Specification/

Closing but feel free to comment (or reopen) if you have more question.
