### ISSUE TITLE
Renaming Enhacement in Web Project.

### ISSUE THREAD

**Issue by Zaigham-Gulzar** [ardalis/CleanArchitecture#720]
Hi,
Under Web Project in **Contributors/GetById**
Suggested renaming is:
**GetById.GetProjectByIdRequest** to **GetById.GetContributorByIdRequest**

I found the class file name to be inconsistent with what it actually is doing inside.

**Comment by ardalis** [comment]
Yeah good catch. Copy paste error. Send a PR?

**Comment by Zaigham-Gulzar** [comment]
Sent under **Zaigham-Gulzar:patch-1**. Happy coding. 😊

**Comment by ardalis** [comment]
Fixed by #721
