### ISSUE TITLE
Mixed SharedKernel : Clean.Architecture and Ardalis

### ISSUE THREAD

**Issue by sdudnic** [ardalis/CleanArchitecture#737]
In the latest version to date in the "sample" project are mixed `SharedKernel` namespaces, using both `Clean.Architecture.SharedKernel ` and `Ardalis.SharedKernel` - seems NOK...

As I understand it should be used the namespaces `NimblePros.SharedKernel`

**Comment by ardalis** [comment]
Ah, yeah, that should probably be fixed. Thanks!

**Comment by KasinathCR** [comment]
This could well be my first Hacktoberfest issue👍 I would like to help on this. Could you please assign me this issue?

**Comment by KasinathCR** [comment]
Hi @ardalis, I've added the PR below fixing the issue. Kindly review it & let me know on any feedback:
https://github.com/ardalis/CleanArchitecture/pull/841

**Comment by ardalis** [comment]
Ok I figured it out. The `NimblePros.SharedKernel` package is meant to only ever be used by the Sample app which also uses NimblePros as its main namespace. I just need to document that better in the NuGet package so I remember it (and maybe add it to the README in the sample if it's not already there).

That being said...

All references to shared kernel in the sample should use the NimblePros.SharedKernel package and namespace.

I'm in the process of doing major updates to the sample myself which will likely include updating the SharedKernel package version so we'll see how this merges in.

**Comment by ardalis** [comment]
Right, exactly. Unfortunately it looks like I just did a Visual Studio Publish to create that Nuget package, so I'll need to do that again sometime soon so that it gets the latest updates that are in Ardalis.SharedKernel. It's on my backlog...
