### ISSUE TITLE
ProjectItemMarkComplete test fails

### ISSUE THREAD

**Issue by sdudnic** [ardalis/CleanArchitecture#739]
in the sample, there is one functional test that fails: ProjectItemMarkComplete

![image](https://github.com/ardalis/CleanArchitecture/assets/35489219/3c7d080a-db38-451d-9604-7874907dfa54)

```
 NimblePros.SampleToDo.FunctionalTests.Projects.ProjectItemMarkComplete.MarksIncompleteItemComplete
   Source: ProjectItemMarkComplete.cs line 23
   Duration: 7 sec

  Message: 
System.Net.Http.HttpRequestException : Response status code does not indicate success: 500 (Internal Server Error).

  Stack Trace: 
HttpResponseMessage.EnsureSuccessStatusCode()
ProjectItemMarkComplete.MarksIncompleteItemComplete() line 32
--- End of stack trace from previous location ---
```

**Comment by samuelbarrionuevo** [comment]
how is the best solution about the stacktrace ?

  Stack Trace: 
HttpResponseMessage.EnsureSuccessStatusCode()
ProjectItemMarkComplete.MarksIncompleteItemComplete() line 32

**Comment by Asafima** [comment]
@sdudnic 
This test requires running an smtp server.
Use:
```shell
docker run --name=papercut -p 25:25 -p 37408:37408 jijiechen/papercut:latest
```

This will setup an smtp server on your docker host.
Run the tests then.
Take a look here:
https://github.com/ardalis/CleanArchitecture/blob/e50dfe981b9459c45791e0a6d7cdcb4cd23f65eb/sample/src/NimblePros.SampleToDo.Core/ProjectAggregate/Handlers/ItemCompletedEmailNotificationHandler.cs#L18

```csharp
  // configure a test email server to demo this works
  // https://ardalis.com/configuring-a-local-test-email-server
  public Task Handle(ToDoItemCompletedEvent domainEvent, CancellationToken cancellationToken)
  {
    Guard.Against.Null(domainEvent, nameof(domainEvent));

    return _emailSender.SendEmailAsync("test@test.com", "test@test.com", $"{domainEvent.CompletedItem.Title} was completed.", domainEvent.CompletedItem.ToString());
  }
```
@ardalis 
Maybe we should add a TestContainer for this functional test.

**Comment by ardalis** [comment]
Yes using a TestContainer makes sense - can someone PR that?
