### ISSUE TITLE
Diagram and Documentation

### ISSUE THREAD

**Issue by baoduy** [ardalis/CleanArchitecture#74]
Hi @ardalis 

This is very interesting template for DDD design and it could be great if you could provide a **diagram** and document of the components of your implementation.

Thanks and Regards
Duy

**Comment by habeebmatrix** [comment]
Agree. If there is a document explaining the overall architecture and how to use the components, it would have been easier.

**Comment by ardalis** [comment]
I'll try to address this soon with some more docs and YouTube videos or something. In the meantime, these are good resources:

- https://www.pluralsight.com/courses/n-tier-apps-part1
- https://www.youtube.com/watch?v=k8cZUW4MS3I
- https://www.slideshare.net/SamNasr2/clean-architecture-with-aspnet-core

**Comment by habeebmatrix** [comment]
Thanks a lot Steve for the prompt answer. Much appreciated.
