### ISSUE TITLE
Support Microsoft.Identity in tenplate

### ISSUE THREAD

**Issue by akbaramd** [ardalis/CleanArchitecture#742]
Hi Ardalis I forked this project and add Microsoft.Identity support to this project

i have some question : 
- why you dont use automapper or other object mapper in this project? 
- can i want to you review my pull request?

@ardalis

**Comment by ardalis** [comment]
I'm not a big fan of Automapper and I've seen developers shoot themselves in the foot with it too many times to recommend it globally.

Sorry I've been remiss in reviewing large PRs, which often end up out of date and full of merge conflicts quickly. I do want to get Auth support into the template, probably as an optional switch when you use `dotnet new`. If you get your PR updated with the latest .NET 9 stuff that's in progress it maybe be something I can work in.
