### ISSUE TITLE
Question regarding 3rd party SDKs (AWS, Azure)

### ISSUE THREAD

**Issue by BradleyDHobbs** [ardalis/CleanArchitecture#79]
We are migrating our .Net 4.5 application to .Net Core and we want to implement clean architecture if possible. 

Currently, some of our business logic (services layer) references 3rd party SDKs. I'll use AWS S3 as an example. So one of our service layer methods would interact with the db using EF, then do something in S3 using the AWS SDK, like uploading a file for example. 

In clean architecture, the readme says this about the Infrastructure layer: "you would also add things like email providers, file access, web api clients, etc. to this project so they're not adding coupling to your Core or UI projects." 

If I am thinking about this correctly, the code to interact with AWS SDK would be in the Infrastructure project. What about the interface? Currently our interface for the S3 logic returns classes specified in the AWS SDK (S3Object), so does that mean the interface would also live in the Infrastructure project? Would you recommend moving the S3 logic out of the service (which would live in Core) and into the controller?

Just needed some insight into what to do with our 3rd party logic that lives alongside our business logic at the moment. I can provide some sample code if this doesn't make sense. 

Thanks

**Comment by ardalis** [comment]
Perfect example. Yes, the AWS-specific code should be limited to Infrastructure and no other project should know about it, if possible. The interface should ideally be abstract enough that it can live in Core. That is, if you have methods now like `S3Object GetObject(S3Key key);` or similar they should instead be something like `Stream GetFileStream(string key);` which has no non-framework dependencies and could have adapters created that use Amazon S3, but could also have Azure Blob Storage adapters or local file system adapters. In fact that one interface might have several such adapters/services that implement it, all located in Infrastructure, and you might choose to use different ones based on environment or user preference or whatever else makes sense for your app.

Hope that's clear - let me know if you have any questions.

**Comment by BradleyDHobbs** [comment]
Awesome! Thanks. Might have others but will tackle those as they come.
