### ISSUE TITLE
Add Architecture Decision Records

### ISSUE THREAD

**Issue by ardalis** [ardalis/CleanArchitecture#829]
Add ADRs to the repo.

Use this as one:
https://github.com/ardalis/CleanArchitecture/issues/649

Resources:
https://ardalis.com/getting-started-with-architecture-decision-records/

**Comment by Zaki2409** [comment]
I would like to contribute on this. Can you assign me this issue?

/assign

**Comment by lukehammer** [comment]
I’m interested in this also.  

I can follow a help also.

**Comment by Zaki2409** [comment]
Hi @ardalis, can you please review it

**Comment by ardalis** [comment]
Fixed by #840
