### ISSUE TITLE
Add Aspire

### ISSUE THREAD

**Issue by ardalis** [ardalis/CleanArchitecture#846]
Add Aspire to the template for .NET 9 version.

- Better yet, make it add aspire only if an option is selected at the command line (e.g. `-aspire`)

**Comment by benjaminmishra** [comment]
Hi @ardalis , long time lurker here , would love to start contributing with this as my first issue. Could you kindly assign this to me ?

**Comment by ardalis** [comment]
@benjaminmishra sure, go for it. I need it done within the next week, and ideally all changes limited to their own folder(s) so that I can use a toggle in the template to opt in. I need to be able to include/exclude folders based on command line choices, like this:
![image](https://github.com/user-attachments/assets/36b11c46-ee6b-4cd9-8a64-455abb7eaa73)


Thanks!

**Comment by benjaminmishra** [comment]
Thank you @ardalis, I will do my best.
