### ISSUE TITLE
Update Template for .NET 9

### ISSUE THREAD

**Issue by ardalis** [ardalis/CleanArchitecture#848]
Update the template to .NET 9.

Consider various .NET 9 (and C# latest) features to include. Comments welcome below.

**Comment by KyleMcMaster** [comment]
I can update the project/build/packages to .NET 9 RC2. I'll let others weigh in on adopting new .NET  and C# features too.

**Comment by KyleMcMaster** [comment]
I believe this can be closed due to the [changes in this commit](https://github.com/ardalis/CleanArchitecture/commit/304ed5540efd53df630af20a9a96fa37571b81cf)

Possibly need a new release before closing?

**Comment by ardalis** [comment]
I think this is the release: https://github.com/ardalis/CleanArchitecture/releases/tag/v10.0.0

So yeah agreed we can close.
