### ISSUE TITLE
Facilitating access to Endpoints with better folder structure

### ISSUE THREAD

**Issue by alirezakamranian** [ardalis/CleanArchitecture#867]
In web layer folder structure can be better especially in Endpoints

**Comment by ardalis** [comment]
What do you propose?

**Comment by alirezakamranian** [comment]
> What do you propose?

My suggestion is that, for example, a folder should be created in the Contributors for each operation such as delete, update, etc., and the request, response, validator, and other files related to each operation should be placed in its own folder so that it is easy to access them.

**Comment by ardalis** [comment]
If you prefer that approach you're welcome to adopt it. We could even support it via a flag so something like `dotnet new clean-arch -use-endpoint-subfolders` would use that behavior. Personally I prefer fewer folders and the ability to "link" the files together using Visual Studio's naming convention:
![image](https://github.com/user-attachments/assets/9553e6f8-fd61-4e6c-9346-a647cd4274d5)
