### ISSUE TITLE
Update Visual Studio Template to use latest .NET Core 3.0 Version

### ISSUE THREAD

**Issue by efleming18** [ardalis/CleanArchitecture#89]
There is a visual studio template for this repo [here](https://github.com/GregTrevellick/CleanArchitecture) which is on the .NET Core 2.1 version of the code. We should update this to be the latest 3.0 version.

@GregTrevellick would you be able to/interesting in updating it?

**Comment by GregTrevellick** [comment]
Yes thanks Eric, I've been intending to merge Steve's latest updates into the VS template for a while, so will do ASAP.

**Comment by efleming18** [comment]
Awesome! :) Thanks, @GregTrevellick !

**Comment by GregTrevellick** [comment]
Hi Eric, I have just published v1.0.6 to the marketplace with all the latest commits from Steve's master branch, so feel free to have a play. Greg

**Comment by ardalis** [comment]
thanks
