### ISSUE TITLE
The dispatch method and all event are never raised

### ISSUE THREAD

**Issue by OneUX** [ardalis/CleanArchitecture#91]
If you try to complete "ToDoItem" the handlers are never registered or handled. I tried to register the Handlers as follows in the container but still does not work. 

var handlers = Assembly.GetAssembly(typeof(IHandle<>));
builder.RegisterAssemblyTypes(handlers).AsImplementedInterfaces();

**Comment by ardalis** [comment]
I think this was fixed by #88. Can you confirm?

**Comment by ardalis** [comment]
The issue of not having Autofac discover the handlers registered in the Core project was a result of adding the SharedKernel project to the solution. The type we were previously using to detect the Core project moved to SharedKernel and not new type as added to tell Autofac to scan Core. The PR #88 fixed that - this line ensures handlers in Core are discovered:

https://github.com/ardalis/CleanArchitecture/blob/master/src/CleanArchitecture.Infrastructure/ContainerSetup.cs#L24

Do you have that line, or something similar such that Autofac is scanning the Core assembly? Are your handlers in Core?

**Comment by OneUX** [comment]
I am using very structure of the projects and trying to use DDD structure, different domains for different subjects. What I found that when handlers is being cast to object, the values of them gets null, please check the screenshot below. 
![image](https://user-images.githubusercontent.com/47757583/70535972-3d725400-1b5e-11ea-9ba7-0b318d69a605.png)

**Comment by ardalis** [comment]
Hey @OneUX if this is still a problem can you open a new issue? I think this is working now.
