### ISSUE TITLE
Is the namespace correct for the classes in SharedKernel?

### ISSUE THREAD

**Issue by PrintsCharming** [ardalis/CleanArchitecture#93]
The classes use CleanArchitecture.**Core**.SharedKernel while the interfaces use CleanArchitecture.SharedKernel.Interfaces

Seems like the classes would use CleanArchitecture.SharedKernel...unless I'm missing something. Which is totally possible.

**Comment by ardalis** [comment]
They shouldn’t say Core. Sounds like it was missed during the refactor. Want to make a pull request?

**Comment by PrintsCharming** [comment]
Submitted. Cheers!
