### ISSUE TITLE
[Q] What is proper namespace for class which uses as method parameter?

### ISSUE THREAD

**Issue by dehghani-mehdi** [ardalis/CleanArchitecture#95]
Hi,

As you didn't add any example of this, I want to know what is proper namespace for such a class. e.g: `public void Foo (Bar bar) { ... }`

The `Bar` class is `DTO` here? _btw I'm not talking about any data related situation here, `Foo` is just a method, maybe it just add 2 number._

**Comment by ardalis** [comment]
It depends on what the service/class is doing. It could go in Core, Infrastructure, or Web. It might even be useful to many applications and go into SharedKernel. There's not enough information here to answer your question.

**Comment by dehghani-mehdi** [comment]
@ardalis thanks for the reply.

You mentioned layers. it could be interesting to know about layer though. but I was talking about the namespace. for example:

```
public bool SendSms(Parameter p) { ... }

public class Parameter { ... }
```

Let's say the `Parameter` class lives in Core layer. (it could be wrong though), I think this class can not be in the root of Core, there should be a directory/namespace for it (and maybe other parameter classes). I'm looking for advice for this namespace.

If is possible also consider some library, e,g nuget package, in such a project, what is the proper namespace for this kind of classes? _I mean outside of Clean Architecture and full web project._

**Comment by ardalis** [comment]
Yes, I think DTO or something similar, perhaps more intention-revealing, like Commands, would make sense. Parameter objects like this one are often Commands or Events so those are the two kinds of DTOs that first come to mind for naming a folder full of these objects.
