### ISSUE TITLE
[Q] SharedKernel and Core

### ISSUE THREAD

**Issue by fabercs** [ardalis/CleanArchitecture#97]
I am trying to understand what SharedKernel is for. It is expressed that

> ..types that would likely be shared between multiple projects..

This is what Core project stands for, isn't it? Any other projects in the solution always references the Core project, so what I need to share accross solution can be resided in the Core. Am I wrong?

**Comment by SteppingRazor** [comment]
_"multiple projects"_ in this case means more like multiple solutions.
In general SharedKernel suppose to contain things so commonly used that is worth to keep them in different project or ideally in private nuget package, so it can be easily reused not only across this solution but many other.

**Comment by ardalis** [comment]
As @SteppingRazor says, SharedKernel is meant to be shared between different projects in the "company projects" sense, not Visual Studio projects. In DDD terms, it would be shared artifacts that span multiple *bounded contexts*. I find it's a good thing to split out into a separate build and, ideally, to reference it as a nuget package in your "real world" environment.
